server.port: ${PORT:8661}
spring.application.name: eureka-server

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

employeesDashboard:
  endpoints:
    - "https://employee-crud-service.herokuapp.com"
    - "https://service-employees.herokuapp.com"
    - "https://employee-zuul-proxy.herokuapp.com"